version: '3'

services:
  backend-service:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:5001

  frontend-service:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - backend-service
